// DeFiScan adapter — raw JSON snapshots → per-protocol TTL fragments.
//
// Reads every output/<YYYY-MM-DD>.json snapshot under this adapter folder,
// emits one TTL file per (protocol, snapshot date) into
// data/ontology/protocols/<ontologyDir>/defiscan.<YYYY-MM-DD>.ttl.
// Every claim carries rfp:observedAt = snapshot date.
//
// SKIP_SLUGS: aave-v3 has a rich hand-curated defiscan.ttl already (~10 narrative Finding
// triples not in the scrape). Until the adapter learns to emit those, we skip aave.
// Other 19 protocols are regenerated each run.

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { slugToOntologyDir } from '../../build/lib/registry.mjs';

const ROOT = path.resolve(import.meta.dirname, '..', '..', '..');
const ADAPTER_DIR = import.meta.dirname;
const OUTPUT_DIR = path.join(ADAPTER_DIR, 'output');
const ONT_PROTOCOLS = path.join(ROOT, 'data', 'ontology', 'protocols');

const SKIP_SLUGS = new Set(['aave']);   // hand-curated coverage preserved

// DeFiScan's 5-axis risk array order (matches defiscan.info/framework spec)
const RISK_AXES = ['chain', 'upgradeability', 'autonomy', 'exit-window', 'accessibility'];

const ttlEscape = (s) => String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');

function emitTtlForProtocol(slug, scrape, snapshotDate) {
  const ontDir = slugToOntologyDir(slug);
  const subject = `<https://relatum.xyz/ns/protocol/${slug}/ethereum>`;
  const ns = `<https://relatum.xyz/ns/protocol/${slug}/`;
  const lines = [];
  lines.push('@prefix rfp:  <https://relatum.xyz/ns/rfp#> .');
  lines.push('@prefix feed: <https://relatum.xyz/ns/feed/> .');
  lines.push('@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .');
  lines.push('@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .');
  lines.push('');
  lines.push(`# Generated by data/adapters/defiscan/to-ttl.mjs from output/${snapshotDate}.json`);
  lines.push(`# Slug: ${slug} · Snapshot date: ${snapshotDate}`);
  lines.push('');

  const sourceUrl = scrape.deployments?.[0]?.website
    ? `https://defiscan.info/projects/${scrape.deployments[0].defiscan_slug || slug}/ethereum`
    : `https://defiscan.info/projects/${slug}`;

  if (!scrape.covered) {
    const reason = scrape.reason || 'Not in DeFiScan registry.';
    lines.push(`${ns}defiscan-coverage-${snapshotDate}> a rfp:CoverageStatement ;`);
    lines.push(`    rfp:about ${subject} ;`);
    lines.push(`    rfp:coverageStatus "notCovered" ;`);
    lines.push(`    rfp:coverageReason "${ttlEscape(reason)}" ;`);
    lines.push(`    rfp:observedAt "${snapshotDate}T00:00:00Z"^^xsd:dateTime ;`);
    lines.push(`    rfp:sourceURL "${sourceUrl}"^^xsd:anyURI ;`);
    lines.push(`    rfp:statedBy feed:defiscan .`);
    lines.push('');
    return lines.join('\n');
  }

  // Pick the Ethereum chain entry from the first deployment; fall back to any chain
  const deployment = scrape.deployments?.[0];
  if (!deployment) return null;
  const chainName = deployment.chains?.ethereum ? 'ethereum' : Object.keys(deployment.chains || {})[0];
  if (!chainName) return null;
  const chainEntry = deployment.chains[chainName];
  const publishDate = chainEntry.publish_date || snapshotDate;

  // Coverage statement (covered)
  lines.push(`${ns}defiscan-coverage-${snapshotDate}> a rfp:CoverageStatement ;`);
  lines.push(`    rfp:about ${subject} ;`);
  lines.push(`    rfp:coverageStatus "covered" ;`);
  lines.push(`    rfp:observedAt "${publishDate}T00:00:00Z"^^xsd:dateTime ;`);
  lines.push(`    rfp:sourceURL "${sourceUrl}"^^xsd:anyURI ;`);
  lines.push(`    rfp:statedBy feed:defiscan .`);
  lines.push('');

  // Stage rating (0/1/2)
  if (chainEntry.stage !== undefined && chainEntry.stage !== null) {
    lines.push(`${ns}defiscan-stage-${snapshotDate}> a rfp:Rating ;`);
    lines.push(`    rdfs:label "DeFiScan Stage classification" ;`);
    lines.push(`    rfp:about ${subject} ;`);
    lines.push(`    rfp:dimension "Stage" ;`);
    lines.push(`    rfp:ratingScale "Stage 0..2" ;`);
    lines.push(`    rfp:ratingValue "${chainEntry.stage}" ;`);
    lines.push(`    rfp:observedAt "${publishDate}T00:00:00Z"^^xsd:dateTime ;`);
    lines.push(`    rfp:sourceURL "${sourceUrl}"^^xsd:anyURI ;`);
    lines.push(`    rfp:statedBy feed:defiscan .`);
    lines.push('');
  }

  // 5-axis risks (L/M/H)
  const risks = chainEntry.risks || [];
  RISK_AXES.forEach((axis, i) => {
    const value = risks[i];
    if (!value) return;
    lines.push(`${ns}defiscan-risk-${axis}-${snapshotDate}> a rfp:Rating ;`);
    lines.push(`    rfp:about ${subject} ;`);
    lines.push(`    rfp:dimension "${axis === 'chain' ? 'Chain' : axis.replace(/-/g, ' ').replace(/^./, c => c.toUpperCase())}" ;`);
    lines.push(`    rfp:ratingScale "L/M/H" ;`);
    lines.push(`    rfp:ratingValue "${value}" ;`);
    lines.push(`    rfp:observedAt "${publishDate}T00:00:00Z"^^xsd:dateTime ;`);
    lines.push(`    rfp:sourceURL "${sourceUrl}"^^xsd:anyURI ;`);
    lines.push(`    rfp:statedBy feed:defiscan .`);
    lines.push('');
  });

  return lines.join('\n');
}

export async function run() {
  const snapshots = (await readdir(OUTPUT_DIR)).filter(f => f.endsWith('.json'));
  if (!snapshots.length) {
    console.log('  no snapshots in output/');
    return 0;
  }
  let written = 0;
  for (const file of snapshots) {
    const date = file.replace(/\.json$/, '');
    const raw = JSON.parse(await readFile(path.join(OUTPUT_DIR, file), 'utf8'));
    for (const [slug, scrape] of Object.entries(raw)) {
      if (SKIP_SLUGS.has(slug)) continue;
      const ttl = emitTtlForProtocol(slug, scrape, date);
      if (!ttl) continue;
      const ontDir = slugToOntologyDir(slug);
      const outDir = path.join(ONT_PROTOCOLS, ontDir);
      await mkdir(outDir, { recursive: true });
      const outPath = path.join(outDir, `defiscan.${date}.ttl`);
      await writeFile(outPath, ttl);
      written++;
    }
    console.log(`  ${file}: wrote TTL for ${Object.keys(raw).length - SKIP_SLUGS.size} protocols`);
  }
  return written;
}

import { fileURLToPath } from 'node:url';
if (path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  console.log('defiscan to-ttl');
  const n = await run();
  console.log(`done — ${n} TTL file(s) emitted`);
}
